# Import Libaries

In [89]:
import numpy as np
import pandas as pd

# Importing Data

In [90]:
crop = pd.read_csv("dataset.csv")
crop.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [91]:
crop.shape

(8796, 8)

In [92]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8796 entries, 0 to 8795
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            8796 non-null   int64  
 1   P            8796 non-null   int64  
 2   K            8796 non-null   int64  
 3   temperature  8796 non-null   float64
 4   humidity     8796 non-null   float64
 5   ph           8796 non-null   float64
 6   rainfall     8796 non-null   float64
 7   label        8796 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 549.9+ KB


In [93]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [94]:
crop.duplicated().sum()

np.int64(1474)

In [95]:
crop.describe()

N            P            K  temperature     humidity  \
count  8796.000000  8796.000000  8796.000000  8796.000000  8796.000000   
mean     61.637449    49.464643    49.754548    25.452016    72.925615   
std      43.925435    26.425013    42.787967     5.056197    18.883838   
min       0.000000     5.000000     5.000000     1.180000    14.258040   
25%      25.000000    30.000000    20.000000    22.676000    60.978766   
50%      50.000000    50.000000    35.000000    25.833333    81.135589   
75%      89.000000    60.000000    60.000000    28.545455    86.038534   
max     180.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  8796.000000  8796.000000  
mean      6.014539   424.069989  
std       0.804694   552.251833  
min       3.504752     3.274569  
25%       5.420000    75.320000  
50%       5.960000   143.315945  
75%       6.528461   689.880000  
max       9.935091  3322.060000

In [96]:
crop['label'].value_counts()

label
potato          461
onion           383
sorghum         367
sunflower       362
rapeseed        361
ragi            293
horsegram       272
wheat           264
turmeric        259
sweet_potato    241
lentil          200
kidneybeans     200
pigeonpeas      200
mothbeans       200
mungbean        200
blackgram       200
rice            200
maize           200
chickpea        200
coconut         200
papaya          200
orange          200
apple           200
muskmelon       200
watermelon      200
grapes          200
mango           200
banana          200
pomegranate     200
coffee          200
cotton          200
jute            200
soybean         196
barley          192
coriander       190
garlic          180
blackpepper      71
tomato           43
brinjal          43
cardamom         41
okra             32
pineapple        24
cabbage          21
cauliflower      18
jackfruit        16
cucumber         14
drumstick        14
radish           11
bottle_gourd     11
bitter_gourd  

# Encoding

In [97]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22
}
crop['crop_num']=  crop['label'].map(crop_dict)

In [98]:
crop

N   P   K  temperature   humidity        ph    rainfall  label  \
0     90  42  43    20.879744  82.002744  6.502985  202.935536   rice   
1     85  58  41    21.770462  80.319644  7.038096  226.655537   rice   
2     60  55  44    23.004459  82.320763  7.840207  263.964248   rice   
3     74  35  40    26.491096  80.158363  6.980401  242.864034   rice   
4     78  42  42    20.130175  81.604873  7.628473  262.717340   rice   
...   ..  ..  ..          ...        ...       ...         ...    ...   
8791  60  30  30     1.180000  83.345432  6.500000  241.780000  wheat   
8792  60  30  30    12.500000  78.695522  6.500000  140.520000  wheat   
8793  60  30  30    14.600000  81.260205  6.400000  169.820000  wheat   
8794  60  30  30    16.820000  70.430798  6.900000    9.627044  wheat   
8795  60  30  30    18.920000  70.679462  6.110000   70.598000  wheat   

      crop_num  
0          1.0  
1          1.0  
2          1.0  
3          1.0  
4          1.0  
...        ...  
8791       NaN  
8792       NaN  
8793       NaN  
8794       NaN  
8795       NaN  

[8796 rows x 9 columns]

In [99]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536       1.0
1  85  58  41    21.770462  80.319644  7.038096  226.655537       1.0
2  60  55  44    23.004459  82.320763  7.840207  263.964248       1.0
3  74  35  40    26.491096  80.158363  6.980401  242.864034       1.0
4  78  42  42    20.130175  81.604873  7.628473  262.717340       1.0

# Train Test Split

In [100]:
crop = crop.dropna(subset=['crop_num'])
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [101]:
X

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
8527   97  12  47    25.287846  89.636679  6.765095   58.286977
8528  110   7  45    26.638386  84.695469  6.189214   48.324286
8529   96  18  50    25.331045  84.305338  6.904242   41.532187
8530   83  23  55    26.897502  83.892415  6.463271   43.971937
8531  120  24  47    26.986037  89.413849  6.260839   58.548767

[4400 rows x 7 columns]

In [102]:
y

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ... 
8527    10.0
8528    10.0
8529    10.0
8530    10.0
8531    10.0
Name: crop_num, Length: 4400, dtype: float64

In [103]:
y.shape

(4400,)

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [106]:
X_train

N    P    K  temperature   humidity        ph    rainfall
122    74   56   22    18.283622  66.659528  6.829199   80.975733
1769   54   67   52    35.676673  93.306419  6.586107  141.338117
1220   39  145  201    36.731266  80.589319  5.775600   72.242308
44     85   52   45    26.313555  82.366990  7.224286  265.535594
289    22   60   85    18.839291  14.740719  7.811998   94.781896
...   ...  ...  ...          ...        ...       ...         ...
4536   31   29   26    28.223734  47.405191  5.024125   97.768323
466    29   78   25    19.959917  59.331578  5.982855  195.787103
4184   95   57   41    23.249256  73.653468  6.434611  184.767486
4864  102   11   45    29.031673  93.126032  6.355443   24.155912
860    32   78   22    23.970814  62.355576  7.007038   53.409060

[3520 rows x 7 columns]


# Scale the features using MinMaxScaler

In [107]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [108]:
X_train

array([[0.52857143, 0.36428571, 0.085     , ..., 0.61128258, 0.51699409,
        0.21830327],
       [0.38571429, 0.44285714, 0.235     , ..., 0.92212835, 0.47919018,
        0.43516203],
       [0.27857143, 1.        , 0.98      , ..., 0.77377871, 0.35314597,
        0.18692745],
       ...,
       [0.67857143, 0.37142857, 0.18      , ..., 0.69286947, 0.45563056,
        0.59118699],
       [0.72857143, 0.04285714, 0.2       , ..., 0.92002407, 0.44331886,
        0.01417159],
       [0.22857143, 0.52142857, 0.085     , ..., 0.5610754 , 0.54465022,
        0.11926686]], shape=(3520, 7))

# Training Models

In [109]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}


for name, model in models.items():
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)

    print(f"{name}  with accuracy : {accuracy_score(y_test,ypred)}")
    print("Confusion matrix : ",confusion_matrix(y_test,ypred))
    print("==========================================================")


Logistic Regression  with accuracy : 0.9590909090909091
Confusion matrix :  [[32  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 42  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 52  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  1  0  0 25  0  0  0  1  0  0  0  0  0  0  2  0  0  0  0  0]
 [ 0  0  0  0  1  0 37  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 47  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 41  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1 39  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 50  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 42  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  

In [110]:
from sklearn.ensemble import RandomForestClassifier

# Configure Random Forest to prevent deep tree growth
rfc = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rfc.fit(X_train, y_train)
ypred = rfc.predict(X_test)
accuracy = accuracy_score(y_test, ypred)

print(f" {accuracy}")


 0.9954545454545455


In [111]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.9977272727272727

# Predictive System

In [112]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    print(prediction)
    return prediction[0]

In [113]:
# new inputs


N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20.]
Kidneybeans is a best crop to be cultivated 


In [114]:
# new inputs 2


N = 100
P = 90
k = 100
temperature = 50.0
humidity = 90.0
ph = 100
rainfall = 202.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20.]
Kidneybeans is a best crop to be cultivated 


In [115]:
# new inputs 2
N = 10
P = 10
k = 10
temperature = 15.0
humidity = 80.0
ph = 4.5
rainfall = 10.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20.]
Kidneybeans is a best crop to be cultivated 


In [116]:
import pickle
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# 1. Fit the scalers on your training data
ms = MinMaxScaler()
ms.fit(X)  # X = full dataset or X_train (features only)

sc = StandardScaler()
sc.fit(ms.transform(X))  # Standardize AFTER MinMax scaling

# 2. Transform data and train your model
X_scaled = sc.transform(ms.transform(X))
model.fit(X_scaled, y)  # Train on scaled data

# 3. Save model and scalers
pickle.dump(model, open('model.pkl', 'wb'))
pickle.dump(sc, open('standscaler.pkl', 'wb'))
pickle.dump(ms, open('minmaxscaler.pkl', 'wb'))

